apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ak-outpost-svc.yaml
  - ciliumnetpol-ceph-osd.yaml
  - ciliumnetpol-eso-webhook.yaml
  - ciliumnetpol-grafana-prometheus.yaml
  - ciliumnetpol-pve-scrape.yaml
  - ciliumnetpol-grafana-pg.yaml
