apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gotify-secret
  namespace: gotify
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: gotify-secret
    creationPolicy: Owner
  data:
    - secretKey: admin-password
      remoteRef:
        key: /gotify/admin-password
    - secretKey: alertmanager-token
      remoteRef:
        key: /gotify/ALERTMANAGER_TOKEN
