apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lighthouse-ci-pvc
  namespace: lighthouse-ci
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd
  resources:
    requests:
      storage: 2Gi
