apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-secret
  namespace: vaultwarden
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: vaultwarden-secret
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: /vaultwarden/DATABASE_URL
    - secretKey: ADMIN_TOKEN
      remoteRef:
        key: /vaultwarden/ADMIN_TOKEN
    - secretKey: DOMAIN
      remoteRef:
        key: /vaultwarden/DOMAIN
    - secretKey: SIGNUPS_ALLOWED
      remoteRef:
        key: /vaultwarden/SIGNUPS_ALLOWED
