apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://vmware-tanzu.github.io/helm-charts
    chart: velero
    targetRevision: "*"
    helm:
      values: |
        credentials:
          useSecret: true
          existingSecret: velero-b2-credentials
        configuration:
          backupStorageLocation:
            - name: default
              provider: aws
              bucket: yanatech-velero
              config:
                region: eu-central-003
                s3Url: https://s3.eu-central-003.backblazeb2.com
                s3ForcePathStyle: "true"
          volumeSnapshotLocation:
            - name: default
              provider: aws
              config:
                region: eu-central-003
        initContainers:
          - name: velero-plugin-for-aws
            image: velero/velero-plugin-for-aws:v1.10.0
            volumeMounts:
              - mountPath: /target
                name: plugins
        schedules:
          weekly-backup:
            schedule: "0 2 * * 0"
            template:
              ttl: 720h
              excludedNamespaces:
                - kube-system
                - kube-public
                - kube-node-lease
                - default
                - cilium-secrets
                - metallb-system
                - ceph-csi-rbd
                - cnpg-system
                - external-secrets
                - reloader
                - kured
                - goldilocks
                - keda
                - argo-rollouts
                - immich
        snapshotsEnabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
