apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ml-predictor-secret
  namespace: yana-stocks
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: ml-predictor-secret
    creationPolicy: Owner
  data:
    - secretKey: MONGODB_URI
      remoteRef:
        key: /yana-stocks/ml-predictor/MONGODB_URI
    - secretKey: MINIO_ACCESS_KEY
      remoteRef:
        key: /yana-stocks/ml-predictor/MINIO_ACCESS_KEY
    - secretKey: MINIO_SECRET_KEY
      remoteRef:
        key: /yana-stocks/ml-predictor/MINIO_SECRET_KEY
    - secretKey: SENTRY_DSN
      remoteRef:
        key: /yana-stocks/ml-predictor/SENTRY_DSN
