apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shared-services-deployment
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  project: default
  source:
    repoURL: https://github.com/akann/shared-services.git
    targetRevision: HEAD
    path: k8s
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: shared-services
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: email-service
      jsonPointers:
        - /spec/replicas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
