apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: runners-yana-stocks
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  project: default
  source:
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    chart: gha-runner-scale-set
    targetRevision: "0.9.3"
    helm:
      valuesObject:
        githubConfigUrl: https://github.com/akann/yana-stocks
        githubConfigSecret: github-pat
        minRunners: 0
        maxRunners: 4
        controllerServiceAccount:
          namespace: actions-runner
          name: actions-runner-controller-gha-rs-controller
        template:
          spec:
            containers:
              - name: runner
                image: ghcr.io/actions/actions-runner:latest
                resources:
                  requests:
                    cpu: "1"
                    memory: 2Gi
                  limits:
                    cpu: "2"
                    memory: 4Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: actions-runner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
