apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-pat
  namespace: actions-runner
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: github-pat
    creationPolicy: Owner
  data:
    - secretKey: github_token
      remoteRef:
        key: /actions-runner/github_token
