apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: k8s-apps-runner
  namespace: actions-runner
spec:
  template:
    spec:
      repository: akann/k8s-apps
      labels:
        - k8s-apps
      image: summerwind/actions-runner:latest
      resources:
        requests:
          cpu: "1"
          memory: 2Gi
        limits:
          cpu: "2"
          memory: 4Gi
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: k8s-apps-runner-hra
  namespace: actions-runner
spec:
  scaleTargetRef:
    name: k8s-apps-runner
  minReplicas: 0
  maxReplicas: 3
  metrics:
    - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
      repositoryNames:
        - akann/k8s-apps
