apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: yana-forex-runner
  namespace: actions-runner
spec:
  template:
    spec:
      repository: akann/yana-forex
      labels:
        - yana-forex
      image: summerwind/actions-runner:latest
      resources:
        requests:
          cpu: "1"
          memory: 2Gi
        limits:
          cpu: "2"
          memory: 4Gi
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: yana-forex-runner-hra
  namespace: actions-runner
spec:
  scaleTargetRef:
    name: yana-forex-runner
  minReplicas: 0
  maxReplicas: 4
  metrics:
    - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
      repositoryNames:
        - akann/yana-forex
