apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: turbo-cache-secret
  namespace: yana-stocks
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: turbo-cache-secret
    creationPolicy: Owner
  data:
    - secretKey: TURBO_TOKEN
      remoteRef:
        key: /yana-stocks/turbo-cache/TURBO_TOKEN
    - secretKey: MINIO_ACCESS_KEY
      remoteRef:
        key: /yana-stocks/turbo-cache/MINIO_ACCESS_KEY
    - secretKey: MINIO_SECRET_KEY
      remoteRef:
        key: /yana-stocks/turbo-cache/MINIO_SECRET_KEY
