apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/headlamp/
    chart: headlamp
    targetRevision: 0.42.0
    helm:
      releaseName: headlamp
      values: |
        config:
          oidc:
            clientID: dJN1D8qo4gka5QZLLUoWkxSQiYAfenM9jxOyUVRA
            clientSecretName: headlamp-oidc-secret
            clientSecretKey: client-secret
            issuerURL: https://auth.yanatech.co.uk/application/o/headlamp/
            scopes: "openid,profile,email,groups"
            useAccessToken: false
            useCookie: false
            secret:
              create: false
              name: "oidc"
        ingress:
          enabled: true
          ingressClassName: nginx
          hosts:
            - host: headlamp.yanatech.co.uk
              paths:
                - path: /
                  type: Prefix
          tls:
            - secretName: wildcard-yanatech-tls
              hosts:
                - headlamp.yanatech.co.uk
  destination:
    server: https://kubernetes.default.svc
    namespace: headlamp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: headlamp
      namespace: headlamp
      jsonPointers:
        - /spec/template/spec/hostUsers
