apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: price-processor-secret
  namespace: yana-stocks
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: price-processor-secret
    creationPolicy: Owner
  data:
    - secretKey: MONGODB_URI
      remoteRef:
        key: /yana-stocks/price-processor/MONGODB_URI
    - secretKey: REDIS_URL
      remoteRef:
        key: /yana-stocks/price-processor/REDIS_URL
    - secretKey: ALPACA_API_KEY
      remoteRef:
        key: /yana-stocks/price-ingestor/ALPACA_API_KEY
    - secretKey: ALPACA_API_SECRET
      remoteRef:
        key: /yana-stocks/price-ingestor/ALPACA_API_SECRET
