apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: price-processor-secret
  namespace: yana-stocks
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: price-processor-secret
    creationPolicy: Owner
  data:
    - secretKey: MONGODB_URI
      remoteRef:
        key: /yana-stocks/price-processor/MONGODB_URI
    - secretKey: REDIS_URL
      remoteRef:
        key: /yana-stocks/price-processor/REDIS_URL
    - secretKey: MASSIVE_API_KEY
      remoteRef:
        key: /yana-stocks/MASSIVE_API_KEY
    - secretKey: TWELVE_DATA_API_KEY
      remoteRef:
        key: /yana-stocks/TWELVE_DATA_API_KEY
    - secretKey: SENTRY_DSN
      remoteRef:
        key: /yana-stocks/price-processor/SENTRY_DSN
