apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicurio-registry
  namespace: apicurio
  labels:
    app: apicurio-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apicurio-registry
  template:
    metadata:
      labels:
        app: apicurio-registry
    spec:
      containers:
        - name: apicurio-registry
          image: quay.io/apicurio/apicurio-registry-sql:2.5.8.Final
          ports:
            - containerPort: 8080
          env:
            - name: REGISTRY_DATASOURCE_URL
              value: jdbc:postgresql://pg-main-rw.cnpg-clusters.svc.cluster.local:5432/apicurio
            - name: REGISTRY_DATASOURCE_USERNAME
              value: apicurio
            - name: REGISTRY_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: apicurio-secret
                  key: db-password
            - name: REGISTRY_AUTH_ENABLED
              value: "true"
            - name: REGISTRY_AUTH_URL
              value: https://auth.yanatech.co.uk/application/o/apicurio/
            - name: REGISTRY_AUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: apicurio-secret
                  key: oidc-client-id
            - name: REGISTRY_AUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: apicurio-secret
                  key: oidc-client-secret
            - name: REGISTRY_AUTH_ROLE_SOURCE
              value: token
            - name: REGISTRY_UI_AUTH_OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: apicurio-secret
                  key: oidc-client-id
            - name: REGISTRY_UI_AUTH_OIDC_URL
              value: https://auth.yanatech.co.uk/application/o/apicurio/
            - name: QUARKUS_OIDC_AUTH_SERVER_URL
              value: https://auth.yanatech.co.uk/application/o/apicurio/
            - name: QUARKUS_OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: apicurio-secret
                  key: oidc-client-id
            - name: QUARKUS_OIDC_CREDENTIALS_SECRET
              valueFrom:
                secretKeyRef:
                  name: apicurio-secret
                  key: oidc-client-secret
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
