apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: akan-deployment
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  project: default
  source:
    repoURL: https://github.com/akann/akan.git
    targetRevision: HEAD
    path: k8s/akan
  destination:
    server: https://kubernetes.default.svc
    namespace: akan
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
