apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-secret
  namespace: nextcloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: nextcloud-secret
    creationPolicy: Owner
  data:
    - secretKey: db-host
      remoteRef:
        key: /nextcloud/db-host
    - secretKey: db-password
      remoteRef:
        key: /nextcloud/db-password
    - secretKey: db-username
      remoteRef:
        key: /nextcloud/db-username
    - secretKey: nextcloud-password
      remoteRef:
        key: /nextcloud/nextcloud-password
    - secretKey: nextcloud-token
      remoteRef:
        key: /nextcloud/nextcloud-token
    - secretKey: nextcloud-username
      remoteRef:
        key: /nextcloud/nextcloud-username
