apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: yanatech
  namespace: yanatech
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: yanatech
  endpoints:
    - port: http
      path: /api/health
      interval: 30s
