apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: user-service-secret
  namespace: yana-stocks
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: user-service-secret
    creationPolicy: Owner
  data:
    - secretKey: REDIS_URL
      remoteRef:
        key: /yana-stocks/user-service/REDIS_URL
    - secretKey: JWT_SECRET
      remoteRef:
        key: /yana-stocks/user-service/JWT_SECRET
    - secretKey: JWT_REFRESH_SECRET
      remoteRef:
        key: /yana-stocks/user-service/JWT_REFRESH_SECRET
