apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: user-service-secret
  namespace: yana-stocks
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: user-service-secret
    creationPolicy: Owner
  data:
    - secretKey: AUTHENTIK_API_TOKEN
      remoteRef:
        key: /yana-stocks/authentik/API_TOKEN
    - secretKey: SMTP_HOST
      remoteRef:
        key: /yana-stocks/user-service/SMTP_HOST
    - secretKey: SMTP_PORT
      remoteRef:
        key: /yana-stocks/user-service/SMTP_PORT
    - secretKey: SMTP_USERNAME
      remoteRef:
        key: /yana-stocks/user-service/SMTP_USERNAME
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: /yana-stocks/user-service/SMTP_PASSWORD
    - secretKey: SMTP_FROM
      remoteRef:
        key: /yana-stocks/user-service/SMTP_FROM
