apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/akann/k8s-apps
    targetRevision: HEAD
    path: apps/immich
  ignoreDifferences:
    - group: external-secrets.io
      kind: ExternalSecret
      namespace: immich
      jsonPointers:
        - /metadata/annotations
    - group: postgresql.cnpg.io
      kind: Cluster
      namespace: immich
      jsonPointers:
        - /metadata/annotations
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
