apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-b2-credentials
  namespace: immich
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: cnpg-b2-credentials
    creationPolicy: Owner
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: /cnpg-clusters/ACCESS_KEY_ID
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: /cnpg-clusters/ACCESS_SECRET_KEY
