apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: user-service
  namespace: yana-stocks
  annotations:
    kubernetes.io/ingress.class: kong
username: user-service
credentials:
  - user-service-jwt-credential
