apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: authentik
  namespace: yana-stocks
  annotations:
    kubernetes.io/ingress.class: kong
username: authentik
credentials:
  - authentik-jwt-credential
