apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: auth-service
  namespace: yana-stocks
  annotations:
    kubernetes.io/ingress.class: kong
username: auth-service
credentials:
  - auth-service-jwt-credential
