apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apicurio
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  project: default
  source:
    repoURL: ghcr.io/eshepelyuk/helm
    chart: apicurio-registry
    targetRevision: "*"
    helm:
      valuesObject:
        registry:
          sql:
            url: jdbc:postgresql://pg-main-rw.cnpg-clusters.svc.cluster.local:5432/apicurio
            username: apicurio
            password: placeholder
          extraEnv:
            - name: REGISTRY_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: apicurio-secret
                  key: db-password
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: apicurio-secret
                  key: db-password
          ingress:
            enabled: true
            ingressClassName: nginx
            host: apicurio.yanatech.co.uk
            tls: true
            annotations:
              nginx.ingress.kubernetes.io/ssl-redirect: "true"

  ignoreDifferences:
    - group: networking.k8s.io
      kind: Ingress
      name: apicurio-apicurio-registry
      namespace: apicurio
      jsonPointers:
        - /spec/tls

  destination:
    server: https://kubernetes.default.svc
    namespace: apicurio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
