apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apicurio
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  project: default
  source:
    repoURL: ghcr.io/eshepelyuk/helm
    chart: apicurio-registry
    targetRevision: "*"
    helm:
      valuesObject:
        storage:
          sql:
            url: jdbc:postgresql://pg-main-rw.cnpg-clusters.svc.cluster.local:5432/apicurio
            username: apicurio
            passwordSecretRef:
              name: apicurio-secret
              key: db-password

        ingress:
          enabled: true
          ingressClassName: nginx
          host: apicurio.yanatech.co.uk
          tls:
            - hosts:
                - apicurio.yanatech.co.uk
              secretName: wildcard-yanatech-tls
  destination:
    server: https://kubernetes.default.svc
    namespace: apicurio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
