apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yana-stocks
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "12"
spec:
  project: default
  source:
    repoURL: https://github.com/akann/k8s-apps
    targetRevision: HEAD
    path: apps/yana-stocks
  destination:
    server: https://kubernetes.default.svc
    namespace: yana-stocks
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: price-ingestor
      jsonPointers:
        - /spec/replicas
    - group: apps
      kind: Deployment
      name: price-processor
      jsonPointers:
        - /spec/replicas
    - group: apps
      kind: Deployment
      name: sentiment-analyzer
      jsonPointers:
        - /spec/replicas
    - group: argoproj.io
      kind: Rollout
      jsonPointers:
        - /metadata/annotations/rollout.argoproj.io~1revision
        - /spec/restartAt
    - group: external-secrets.io
      kind: ExternalSecret
      jqPathExpressions:
        - .spec.data[].remoteRef.conversionStrategy
        - .spec.data[].remoteRef.decodingStrategy
        - .spec.data[].remoteRef.metadataPolicy
        - .spec.data[].remoteRef.nullBytePolicy
        - .spec.target.deletionPolicy
        - .spec.target.template.engineVersion
        - .spec.target.template.mergePolicy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - ServerSideDiff=true
