apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - harbor-pull-secret.yaml
  - user-service
  - price-processor
  - portfolio-service
  - portfolio-api
  - price-ingestor
  - sentiment-analyzer
  - ml-predictor
  - frontend
  - kong
