apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongo-express
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: default
  source:
    repoURL: https://github.com/akann/k8s-apps
    path: infrastructure/mongo-express
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: mongo-express
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
