apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongo-express-secret
  namespace: mongo-express
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: mongo-express-secret
    creationPolicy: Owner
  data:
    - secretKey: mongodb-root-password
      remoteRef:
        key: /mongodb/MONGODB_ROOT_PASSWORD
