apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-webhook-monitor-token
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: github-webhook-monitor-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: /argocd/GITHUB_WEBHOOK_MONITOR_TOKEN
