apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin-oauth-secret
  namespace: pgadmin
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: pgadmin-oauth-secret
    creationPolicy: Owner
  data:
    - secretKey: OAUTH2_CLIENT_ID
      remoteRef:
        key: /pgadmin/OAUTH2_CLIENT_ID
    - secretKey: OAUTH2_CLIENT_SECRET
      remoteRef:
        key: /pgadmin/OAUTH2_CLIENT_SECRET
