apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.goauthentik.io
    chart: authentik
    targetRevision: "*"
    helm:
      valuesObject:
        authentik:
          existingSecret:
            secretName: authentik-secret
        postgresql:
          enabled: false
        redis:
          enabled: true
          master:
            persistence:
              storageClass: ceph-rbd
        global:
          env:
            - name: AUTHENTIK_EMAIL__HOST
              value: mail-eu.smtp2go.com
            - name: AUTHENTIK_EMAIL__PORT
              value: "2525"
            - name: AUTHENTIK_EMAIL__USE_TLS
              value: "true"
            - name: AUTHENTIK_EMAIL__USE_SSL
              value: "false"
            - name: AUTHENTIK_EMAIL__FROM
              value: info@yanatech.co.uk
            - name: AUTHENTIK_EMAIL__USERNAME
              value: yanatech.co.uk
            - name: AUTHENTIK_EMAIL__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentik-secret
                  key: AUTHENTIK_EMAIL__PASSWORD
        server:
          automountServiceAccountToken: false
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - authentik.yanatech.co.uk
            tls:
              - hosts:
                  - authentik.yanatech.co.uk
                secretName: wildcard-yanatech-tls
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
