apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.goauthentik.io
    chart: authentik
    targetRevision: "*"
    helm:
      valuesObject:
        authentik:
          existingSecret:
            secretName: authentik-secret
          email:
            host: smtppro.zoho.eu
            port: 465
            use_tls: false
            use_ssl: true
            from: akan@yanatech.org
            username: akan@yanatech.org
        postgresql:
          enabled: false
        redis:
          enabled: true
          master:
            persistence:
              storageClass: ceph-rbd
        server:
          env:
            - name: AUTHENTIK_EMAIL__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentik-secret
                  key: AUTHENTIK_EMAIL__PASSWORD
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - authentik.yanatech.co.uk
            tls:
              - hosts:
                  - authentik.yanatech.co.uk
                secretName: wildcard-yanatech-tls
        worker:
          env:
            - name: AUTHENTIK_EMAIL__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentik-secret
                  key: AUTHENTIK_EMAIL__PASSWORD
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
