apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secret
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: authentik-secret
    creationPolicy: Owner
  data:
    - secretKey: AUTHENTIK_POSTGRESQL__HOST
      remoteRef:
        key: /authentik/AUTHENTIK_POSTGRESQL__HOST
    - secretKey: AUTHENTIK_POSTGRESQL__NAME
      remoteRef:
        key: /authentik/AUTHENTIK_POSTGRESQL__NAME
    - secretKey: AUTHENTIK_POSTGRESQL__PASSWORD
      remoteRef:
        key: /authentik/AUTHENTIK_POSTGRESQL__PASSWORD
    - secretKey: AUTHENTIK_POSTGRESQL__USER
      remoteRef:
        key: /authentik/AUTHENTIK_POSTGRESQL__USER
    - secretKey: AUTHENTIK_REDIS__HOST
      remoteRef:
        key: /authentik/AUTHENTIK_REDIS__HOST
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: /authentik/AUTHENTIK_SECRET_KEY
    - secretKey: AUTHENTIK_EMAIL__PASSWORD
      remoteRef:
        key: /authentik/AUTHENTIK_EMAIL__PASSWORD
