apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  namespace: yana-stocks
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - stocks.yanatech.co.uk
      secretName: wildcard-yanatech-tls
  rules:
    - host: stocks.yanatech.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000
