apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "*"
    helm:
      releaseName: kube-prometheus-stack
      values: |
        alertmanager:
          alertmanagerSpec:
            storage:
              volumeClaimTemplate:
                spec:
                  storageClassName: ceph-rbd
                  resources:
                    requests:
                      storage: 5Gi
        grafana:
          adminPassword: changeme
          envFromSecret: grafana-authentik-secret
          grafana.ini:
            server:
              root_url: https://grafana.yanatech.co.uk
            auth.generic_oauth:
              enabled: true
              name: Authentik
              icon: signin
              client_id: $__env{client_id}
              client_secret: $__env{client_secret}
              scopes: openid email profile
              auth_url: https://auth.yanatech.co.uk/application/o/grafana/authorize/
              token_url: https://auth.yanatech.co.uk/application/o/token/
              api_url: https://auth.yanatech.co.uk/application/o/userinfo/
              role_attribute_path: contains(groups, 'authentik Admins') && 'Admin' || 'Viewer'
              allow_sign_up: true
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - grafana.yanatech.co.uk
            tls:
              - hosts:
                  - grafana.yanatech.co.uk
                secretName: wildcard-yanatech-tls
        prometheus:
          prometheusSpec:
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: ceph-rbd
                  resources:
                    requests:
                      storage: 20Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
