apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-authentik-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: grafana-authentik-secret
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: /monitoring/client_id
    - secretKey: client_secret
      remoteRef:
        key: /monitoring/client_secret
