apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-smtp-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: grafana-smtp-secret
    creationPolicy: Owner
  data:
    - secretKey: smtp_username
      remoteRef:
        key: /yana-stocks/auth-service/SMTP_USERNAME
    - secretKey: smtp_password
      remoteRef:
        key: /yana-stocks/auth-service/SMTP_PASSWORD
    - secretKey: smtp_from
      remoteRef:
        key: /yana-stocks/auth-service/SMTP_FROM
