apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-pg-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: k8s-yana-stocks
    kind: ClusterSecretStore
  target:
    name: grafana-pg-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: auth-service-pg-app
        property: password
