apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-insight
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: default
  source:
    repoURL: https://github.com/akann/k8s-apps
    path: infrastructure/redis-insight
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: redis-insight
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
