apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: csi-rbd-secret
  namespace: ceph-csi-rbd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: csi-rbd-secret
    creationPolicy: Owner
  data:
    - secretKey: userID
      remoteRef:
        key: /ceph-csi-rbd/userID
    - secretKey: userKey
      remoteRef:
        key: /ceph-csi-rbd/userKey
