apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: profile-service
  namespace: yana-stocks
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: profile-service
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
