apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: portfolio-service-secret
  namespace: yana-stocks
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: portfolio-service-secret
    creationPolicy: Owner
  data:
    - secretKey: MONGODB_URI
      remoteRef:
        key: /yana-stocks/portfolio-service/MONGODB_URI
