apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dove-house-tt-deployment
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  project: default
  source:
    repoURL: https://github.com/akann/dove-house-tt.git
    targetRevision: HEAD
    path: k8s/dove-house-tt
  destination:
    server: https://kubernetes.default.svc
    namespace: dove-house-tt
  ignoreDifferences:
    - group: external-secrets.io
      kind: ExternalSecret
      jqPathExpressions:
        - .spec.data[].remoteRef.conversionStrategy
        - .spec.data[].remoteRef.decodingStrategy
        - .spec.data[].remoteRef.metadataPolicy
        - .spec.data[].remoteRef.nullBytePolicy
        - .spec.target.deletionPolicy
        - .spec.target.template.engineVersion
        - .spec.target.template.mergePolicy
    - group: postgresql.cnpg.io
      kind: Cluster
      jqPathExpressions:
        - .spec.affinity
        - .spec.enablePDB
        - .spec.enableSuperuserAccess
        - .spec.failoverDelay
        - .spec.logLevel
        - .spec.maxSyncReplicas
        - .spec.minSyncReplicas
        - .spec.monitoring
        - .spec.postgresGID
        - .spec.postgresUID
        - .spec.primaryUpdateMethod
        - .spec.primaryUpdateStrategy
        - .spec.probes
        - .spec.replicationSlots
        - .spec.smartShutdownTimeout
        - .spec.startDelay
        - .spec.stopDelay
        - .spec.switchoverDelay
        - .spec.bootstrap.initdb.encoding
        - .spec.bootstrap.initdb.localeCType
        - .spec.bootstrap.initdb.localeCollate
        - .spec.managed.roles[].connectionLimit
        - .spec.managed.roles[].ensure
        - .spec.managed.roles[].inherit
        - .spec.backup.barmanObjectStore.target
        - .spec.postgresql.parameters
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
