apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-yanatech
  namespace: ingress-nginx
spec:
  dnsNames:
    - yanatech.co.uk
    - "*.yanatech.co.uk"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: wildcard-yanatech-tls
