apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token-dovehousett
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-token-dovehousett
    creationPolicy: Owner
  data:
    - secretKey: api-token
      remoteRef:
        key: /cert-manager/api-token-dovehousett
