apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sentiment-analyzer-secret
  namespace: yana-stocks
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: sentiment-analyzer-secret
    creationPolicy: Owner
  data:
    - secretKey: ALPACA_API_KEY
      remoteRef:
        key: /yana-stocks/price-ingestor/ALPACA_API_KEY
    - secretKey: ALPACA_API_SECRET
      remoteRef:
        key: /yana-stocks/price-ingestor/ALPACA_API_SECRET
    - secretKey: MONGODB_URI
      remoteRef:
        key: /yana-stocks/sentiment-analyzer/MONGODB_URI
