apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  project: default
  source:
    repoURL: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
    chart: infisical-standalone
    targetRevision: "*"
    helm:
      valuesObject:
        infisical:
          enabled: true
          replicaCount: 2
          image:
            tag: latest-postgres
          autoDatabaseSchemaMigration: true
          existingSecret: infisical-secrets
          kubeSecretRef: infisical-secrets
          ingress:
            enabled: true
            ingressClassName: nginx
            hostname: infisical.yanatech.co.uk
            nginx:
              enabled: false
            tls:
              - secretName: wildcard-yanatech-tls
                hosts:
                  - infisical.yanatech.co.uk
        ingress-nginx:
          enabled: false
          controller:
            replicaCount: 0
            admissionWebhooks:
              enabled: false
        postgresql:
          enabled: false
        redis:
          enabled: true
          architecture: standalone
          auth:
            enabled: false
          master:
            persistence:
              storageClass: ceph-rbd
              size: 5Gi
            podAnnotations:
              backup.velero.io/backup-volumes: redis-data
  ignoreDifferences:
    - group: networking.k8s.io
      kind: Ingress
      name: infisical-ingress
      namespace: infisical
      jsonPointers:
        - /spec/ingressClassName
        - /spec/rules
        - /spec/tls
    - group: apps
      kind: Deployment
      name: infisical-ingress-nginx-controller
      namespace: infisical
    - group: ""
      kind: Service
      name: infisical-ingress-nginx-controller
      namespace: infisical
    - group: ""
      kind: Service
      name: infisical-ingress-nginx-controller-admission
      namespace: infisical
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: infisical-ingress-nginx-admission
      jsonPointers:
        - /webhooks/0/failurePolicy
    - group: networking.k8s.io
      kind: IngressClass
      name: infisical-nginx
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      name: infisical-ingress-nginx
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      name: infisical-ingress-nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: infisical
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
