apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-secret
  namespace: harbor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: harbor-secret
    creationPolicy: Owner
  data:
    - secretKey: HARBOR_ADMIN_PASSWORD
      remoteRef:
        key: /harbor/HARBOR_ADMIN_PASSWORD
    - secretKey: HARBOR_SECRET_KEY
      remoteRef:
        key: /harbor/secretKey
    - secretKey: secretKey
      remoteRef:
        key: /harbor/secretKey
