apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-ingestor
  namespace: yana-stocks
  annotations:
    secret.reloader.stakater.com/reload: "price-ingestor-secret"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: price-ingestor
  template:
    metadata:
      labels:
        app: price-ingestor
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: harbor-pull-secret
      containers:
        - name: price-ingestor
          image: harbor.yanatech.co.uk/yana-stocks/price-ingestor:a9ad4ee0a138244dc7ae37873bccd5b67237a319
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 100
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: MASSIVE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: price-ingestor-secret
                  key: MASSIVE_API_KEY
            - name: KAFKA_BROKERS
              value: "kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
            - name: SYMBOLS
              value: "AAPL,GOOGL,MSFT,AMZN,TSLA,NVDA,META,JPM,V,JNJ"
            - name: OTEL_SERVICE_NAME
              value: "price-ingestor"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://tempo.monitoring.svc.cluster.local:4318"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
