apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-ingestor
  namespace: yana-stocks
  labels:
    app: price-ingestor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: price-ingestor
  template:
    metadata:
      labels:
        app: price-ingestor
    spec:
      containers:
        - name: price-ingestor
          image: harbor.yanatech.co.uk/yana-stocks/price-ingestor:latest
          envFrom:
            - secretRef:
                name: price-ingestor-secrets
          env:
            - name: SYMBOLS
              value: AAPL,GOOGL,MSFT,AMZN,TSLA,NVDA,META,JPM,V,JNJ
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
