apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: price-ingestor
  namespace: yana-stocks
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: price-ingestor
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
