apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: portfolio-api-secret
  namespace: yana-stocks
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: portfolio-api-secret
    creationPolicy: Owner
  data:
    - secretKey: REDIS_URL
      remoteRef:
        key: /yana-stocks/portfolio-api/REDIS_URL
    - secretKey: MONGODB_URI
      remoteRef:
        key: /yana-stocks/portfolio-api/MONGODB_URI
    - secretKey: SENTIMENT_MONGODB_URI
      remoteRef:
        key: /yana-stocks/sentiment-analyzer/MONGODB_URI
