apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongodb-secret
  namespace: mongodb
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: mongodb-secret
    creationPolicy: Owner
  data:
    - secretKey: mongodb-root-password
      remoteRef:
        key: /mongodb/MONGODB_ROOT_PASSWORD
    - secretKey: mongodb-password
      remoteRef:
        key: /mongodb/MONGODB_PASSWORD
