apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongodb-secret
  namespace: mongodb
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: mongodb-secret
    creationPolicy: Owner
    template:
      data:
        mongodb-root-password: "{{ .root_password }}"
        mongodb-passwords: "{{ .password }}"
        mongodb-replica-set-key: "{{ .replica_set_key }}"
  data:
    - secretKey: root_password
      remoteRef:
        key: /mongodb/MONGODB_ROOT_PASSWORD
    - secretKey: password
      remoteRef:
        key: /mongodb/MONGODB_PASSWORD
    - secretKey: replica_set_key
      remoteRef:
        key: /mongodb/MONGODB_REPLICA_SET_KEY
