apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pg-main.yaml
  - external-secret-b2.yaml
  - external-secret-harbor.yaml
  - external-secret-minio.yaml
  - scheduled-backup.yaml
