apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: pg-main-backup
  namespace: cnpg-clusters
spec:
  schedule: "0 2 * * *"
  backupOwnerReference: self
  cluster:
    name: pg-main
